# toolbar:
#   - styleselect | bold italic | undo redo
#   - link
# plugins:
#   - link


theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons1_add:
  - forecolor
  - fontselect
  - formatselect
theme_advanced_styles : "Header 1=header1;Header 2=header2;Header 3=header3;Table Row=tableRow1"

theme_advanced_buttons3_add:
  - tablecontrols
  - fullscreen
  - emotions
  - styleprops
  - preview
  - media
plugins:
  - table
  - fullscreen
  - emotions
  - style
  - preview
  - media

apply_source_formatting : true
theme_advanced_more_colors : true
